version: '3.5'

services:
    claim_mongo:
        container_name: thx_claim_mongo
        image: mongo
        env_file: .env.example
        restart: always
        ports:
            - 27020:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: admin
        volumes:
            - claim-mongo-data:/data/db
            - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
        networks:
            - claim_api

    claim_testnet:
        container_name: thx_claim_testnet
        image: public.ecr.aws/o5j5y3t5/hardhat-thx-artifacts:3.1.5
        networks:
            - claim_api
        ports:
            - '8549:8545'

    claim_mainnet:
        container_name: thx_claim_mainnet
        image: public.ecr.aws/o5j5y3t5/hardhat-thx-artifacts:3.1.5
        networks:
            - claim_api
        ports:
            - '8548:8545'

volumes:
    claim-mongo-data:

networks:
    claim_api: